name: Build, test and publish the image

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  
  build-test-publish:
    name: Build and Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      packages: write
    env:
      MAX_ATTEMPTS: 5
      SLEEP_DURATION: 30
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3


      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          flavor: latest=true
          tags: |
            type=sha,format=short   
            type=raw,value=${{ github.ref_name }}
      
      - name: Build and export to Docker
        uses: docker/build-push-action@v6
        with:
          context: .
          load: true
          tags: ${{ github.ref_name}}

      - name: Debug
        run: |
          docker image ls

      - name: Run container
        run: |
          docker run --rm -d -p 2015:2015 -p 2016:2016 --name redirect-container ${{ github.ref_name }}
      
      - name: Wait for healthy container
        run: |
          for ((i=1; i<=${{ env.MAX_ATTEMPTS }}; i++)); do
            health=$(docker inspect --format='{{.State.Health.Status}}' redirect-container)
            if [[ "$health" = "healthy" ]]; then
              echo "Container is healthy!"; exit 0
            fi
            echo "Waiting for container to become healthy... ($i/${{ env.MAX_ATTEMPTS }})"
            sleep ${{ env.SLEEP_DURATION }}
          done
          echo "Container did not become healthy in time." && docker logs redirect-container && exit 1
      
      - name: Run tests
        run: |
          chmod +x ./scripts/test-redirects.sh
          ./scripts/test-redirects.sh localhost 2015
      
      - name: Stop container
        if: always()
        run: docker stop redirect-container

  
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor}}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      
      - name: Build and push to GitHub Container Registry
        uses: docker/build-push-action@v6.17.0
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          build-args: |
            BUILDKIT_INLINE_CACHE=1

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.32.0
        with:
          image-ref: '${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.version }}'
          severity: 'CRITICAL,HIGH'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'
